# This is a TOML document

title = "Example TOML"

[owner]
name = "John Doe"
dob = 1979-05-27T07:32:00Z # Date and time in ISO 8601 format

[database]
server = "192.168.1.1"
port = 5432
enabled = true

[servers]

  [servers.alpha]
  ip = "10.0.0.1"
  dc = "us-east"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "us-west"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]
hosts = ["alpha", "beta", "gamma"]
